import '@/js/comb.js';
import '@/js/global-buttons.js';
import '@/js/photo-opener.js';
import '@/js/abdul.js';
import '@/js/global-func.js'
import '@/js/captcha.js'
import '@/js/globalCall.js'
import '@/js/contacts_footer.js'
import '@/js/compareCars.js'