import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://xn--80aej9alefdt2f.xn--p1ai/');
  await expect(page.getByRole('link', { name: 'Купить' }).first()).toBeVisible();
  await expect(page.getByRole('link', { name: 'Продать' }).first()).toBeVisible();
  await expect(page.getByRole('link', { name: 'Каталог шин' }).first()).toBeVisible();
  // await expect(page.getByRole('contentinfo').getByText('Россия')).toBeVisible();
  await page.locator('.button__burger').click();
  await page.getByRole('link', { name: 'Купить' }).nth(1).click();
  await expect(page.getByRole('link', { name: 'Купить' }).first()).toBeVisible();
  await expect(page.locator('body')).toContainText('Продать');
  await expect(page.getByRole('heading', { name: 'Автомобили' })).toBeVisible();
  await page.locator('.button__burger').click();
  await page.getByRole('link', { name: 'Продать' }).nth(1).click();
  await expect(page.getByRole('link', { name: 'Купить' }).first()).toBeVisible();
  await page.getByRole('link', { name: 'Продать' }).first().click();
  await expect(page.locator('body')).toContainText('Порядок выкупа автомобиля');
  await page.locator('.button__burger').click();
  await page.getByRole('link', { name: 'Каталог шин' }).nth(1).click();
  await expect(page.getByRole('link', { name: 'Купить' }).first()).toBeVisible();
  // await expect(page.locator('#vitrina_name')).to ContainText('Каталог шин');
  await page.locator('.button__burger').click();
  await page.getByRole('link', { name: 'Автоподбор' }).click();
  await expect(page.getByRole('link', { name: 'Купить' }).first()).toBeVisible();
  await expect(page.locator('body')).toContainText('Что мы проверяем:');
  await page.locator('.button__burger').click();
  await page.getByRole('link', { name: 'Акции' }).click();
  await expect(page.getByRole('link', { name: 'Купить' }).first()).toBeVisible();
  await expect(page.locator('h1')).toContainText('Акции и спецпредложения');
  await page.locator('.button__burger').click();
  await page.getByRole('link', { name: 'Контакты' }).first().click();
  await expect(page.getByRole('link', { name: 'Купить' }).first()).toBeVisible();
  // await expect(page.locator('h1')).toContainText('Адреса дилерских центров');
  await expect(page.getByRole('main')).toContainText('Шинные центры');
  await page.locator('.button__burger').click();
  await page.getByRole('link', { name: 'Партнерам' }).first().click();
  await expect(page.getByRole('link', { name: 'Купить' }).first()).toBeVisible();
  // await expect(page.locator('body')).toContainText('В чем выгода сотрудничествас АВТОСЕТЬ.РФ?');
  await page.locator('.button__burger').click();
  await page.getByRole('link', { name: 'О компании' }).first().click();
  await expect(page.getByRole('heading', { name: 'Автосеть.РФ и Апельсин — группа компаний' })).toBeVisible();
  // await expect(page.locator('body')).toContainText('2005 г.');
  await page.locator('.button__burger').click();
  // await page.getByRole('link', { name: 'Новости' }).click();
  await expect(page.getByRole('heading', { name: 'Новости и статьи' })).toBeVisible();
  // await expect(page.getByRole('main')).toContainText('Страницы: 1 |2 |3 |След.');
  await page.locator('.button__burger').click();
  await page.getByRole('link', { name: 'Вакансии' }).first().click();
  await expect(page.getByRole('link', { name: 'Купить' }).first()).toBeVisible();
  await expect(page.locator('h1')).toContainText('ПРИСОЕДИНЯЙТЕСЬ К НАШЕЙ КОМАНДЕ');
  await page.locator('.button__burger').click();
  await page.getByRole('link', { name: 'Услуги' }).click();
  await expect(page.getByRole('link', { name: 'Купить' }).first()).toBeVisible();
  await expect(page.locator('h1')).toContainText('Услуги Автосеть.рф');
  await page.locator('.button__burger').click();
  await page.getByRole('link', { name: 'Автокредитование', exact: true }).click();
  await expect(page.getByRole('link', { name: 'Купить' }).first()).toBeVisible();
  await expect(page.locator('body')).toContainText('Банки партнеры');
  await expect(page.locator('body')).toContainText('Почему стоит обратиться в Автосеть.рф?');
  await page.locator('.button__burger').click();
  await page.getByRole('link', { name: 'Страхование', exact: true }).click();
  await expect(page.getByRole('link', { name: 'Купить' }).first()).toBeVisible();
  await expect(page.locator('body')).toContainText('Страховые компании');
  await page.locator('.button__burger').click();
  await page.getByRole('link', { name: 'Шинный центр', exact: true }).click();
  await expect(page.getByRole('link', { name: 'Купить' }).first()).toBeVisible();
  await expect(page.locator('body')).toContainText('Таблица индексов скорости и нагрузки шин');
  await page.locator('.button__burger').click();
  await page.getByRole('link', { name: 'Техосмотр' }).click();
  await expect(page.getByRole('link', { name: 'Купить' }).first()).toBeVisible();
  await expect(page.locator('body')).toContainText('Наши услуги и цены');
  await page.locator('.button__burger').click();
  await page.getByRole('link', { name: 'Сервисное обслуживание' }).click();
  await expect(page.getByRole('link', { name: 'Купить' }).first()).toBeVisible();
  await expect(page.locator('body')).toContainText('Наши услуги и цены');
  await page.locator('.button__burger').click();
  await page.getByRole('link', { name: 'Ремонт двигателя' }).click();
  await expect(page.getByRole('link', { name: 'Купить' }).first()).toBeVisible();
  await expect(page.locator('body')).toContainText('Процесс ремонта акпп');
  await page.locator('.button__burger').click();
  await page.getByRole('link', { name: 'Ремонт АКПП' }).click();
  await expect(page.getByRole('link', { name: 'Купить' }).first()).toBeVisible();
  await expect(page.locator('body')).toContainText('Когда без ремонта АКПП не обойтись');
  await page.locator('.button__burger').click();
  await page.getByRole('link', { name: 'Замена масла' }).click();
  await expect(page.getByRole('link', { name: 'Купить' }).first()).toBeVisible();
  await expect(page.locator('body')).toContainText('Почему АВТОСЕТЬ.РФ?');
  await expect(page.locator('body')).toContainText('Наши основные услуги');
});