import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://xn--80aej9aped4f.xn--p1ai/');

  await page.getByRole('banner').getByRole('link', { name: 'Купить' }).click();
  await expect(page.getByRole('banner')).toContainText('Заказать звонок');
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('main').getByRole('link', { name: 'Купить' }).click();
  await expect(page.getByRole('banner').getByRole('link', { name: 'Купить' })).toBeVisible();
  await expect(page.getByRole('banner')).toContainText('Заказать звонок');
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('main').getByRole('link', { name: 'Продать', exact: true }).click();
  await expect(page.getByRole('banner').getByRole('link', { name: 'Купить' })).toBeVisible();
  await expect(page.getByRole('banner')).toContainText('Заказать звонок');
  await page.getByRole('banner').getByRole('button').click();
  await page.getByRole('main').getByRole('link', { name: 'Каталог шин' }).click();
  await expect(page.getByRole('banner').getByRole('link', { name: 'Купить' })).toBeVisible();
  await expect(page.getByRole('banner')).toContainText('Заказать звонок');
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('link', { name: 'Автоподбор' }).click();
  await expect(page.getByRole('banner').getByRole('link', { name: 'Купить' })).toBeVisible();
  await expect(page.getByRole('banner')).toContainText('Заказать звонок');
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('link', { name: 'Акции' }).click();
  await expect(page.getByRole('banner').getByRole('link', { name: 'Купить' })).toBeVisible();
  await expect(page.getByRole('banner')).toContainText('Заказать звонок');
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('main').getByRole('link', { name: 'Контакты' }).click();
  await expect(page.getByRole('banner').getByRole('link', { name: 'Купить' })).toBeVisible();
  await expect(page.getByRole('banner')).toContainText('Заказать звонок');
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('main').getByRole('link', { name: 'Партнерам' }).click();
  await expect(page.getByRole('banner').getByRole('link', { name: 'Купить' })).toBeVisible();
  await expect(page.getByRole('banner')).toContainText('Заказать звонок');
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('main').getByRole('link', { name: 'О компании' }).click();
  await expect(page.getByRole('banner').getByRole('link', { name: 'Купить' })).toBeVisible();
  await expect(page.getByRole('banner')).toContainText('Заказать звонок');
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('link', { name: 'Новости' }).click();
  await expect(page.getByRole('banner').getByRole('link', { name: 'Купить' })).toBeVisible();
  await expect(page.getByRole('banner')).toContainText('Заказать звонок');
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('main').getByRole('link', { name: 'Вакансии' }).click();
  await expect(page.getByRole('banner').getByRole('link', { name: 'Купить' })).toBeVisible();
  await expect(page.getByRole('banner')).toContainText('Заказать звонок');
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('link', { name: 'Услуги' }).click();
  await expect(page.getByRole('banner').getByRole('link', { name: 'Купить' })).toBeVisible();
  await expect(page.getByRole('banner')).toContainText('Заказать звонок');
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('link', { name: 'Автокредитование', exact: true }).click();
  await expect(page.getByRole('banner').getByRole('link', { name: 'Купить' })).toBeVisible();
  await expect(page.getByRole('banner')).toContainText('Заказать звонок');
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('link', { name: 'Страхование', exact: true }).click();
  await expect(page.getByRole('banner').getByRole('link', { name: 'Купить' })).toBeVisible();
  await expect(page.getByRole('banner')).toContainText('Заказать звонок');
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('link', { name: 'Шинный центр', exact: true }).click();
  await expect(page.getByRole('banner').getByRole('link', { name: 'Купить' })).toBeVisible();
  await expect(page.getByRole('banner')).toContainText('Заказать звонок');
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('link', { name: 'Техосмотр' }).click();
  await expect(page.getByRole('banner').getByRole('link', { name: 'Купить' })).toBeVisible();
  await expect(page.getByRole('banner')).toContainText('Заказать звонок');
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('link', { name: 'Сервисное обслуживание' }).click();
  await expect(page.getByRole('banner').getByRole('link', { name: 'Купить' })).toBeVisible();
  await expect(page.getByRole('banner')).toContainText('Заказать звонок');
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('link', { name: 'Ремонт двигателя' }).click();
  await expect(page.getByRole('banner').getByRole('link', { name: 'Купить' })).toBeVisible();
  await expect(page.getByRole('banner')).toContainText('Заказать звонок');
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('link', { name: 'Ремонт АКПП' }).click();
  await expect(page.getByRole('banner').getByRole('link', { name: 'Купить' })).toBeVisible();
  await expect(page.getByRole('banner')).toContainText('Заказать звонок');
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('link', { name: 'Замена масла' }).click();
  await expect(page.getByRole('banner').getByRole('link', { name: 'Купить' })).toBeVisible();
  
});