import { test, expect } from '@playwright/test';

test.describe('Общий тест', () => {
  test('Наличие верхней менюшки на всех страницах', async ({ page }) => {
    await page.goto('http://xn--80aej9alefdt2f.xn--p1ai/');
    await page.getByRole('link', { name: 'Купить' }).first().click();
    await expect(page.getByRole('link', { name: 'КУпить' }).first()).toBeVisible();
    await expect(page.locator('body')).toContainText('Заказать звонок');
    await page.locator('.button__burger').click();
    await page.getByRole('link', { name: 'Купить' }).nth(1).click();
    await expect(page.getByRole('link', { name: 'Купить' }).first()).toBeVisible();
    await expect(page.locator('body')).toContainText('Заказать звонок');
    await page.locator('.button__burger').click();
    await page.getByRole('link', { name: 'Продать' }).nth(1).click();
    await expect(page.getByRole('link', { name: 'Купить' }).first()).toBeVisible();
    await expect(page.locator('body')).toContainText('Заказать звонок');
    await page.locator('.button__burger').click();
    await page.getByRole('link', { name: 'Каталог шин' }).nth(1).click();
    await expect(page.getByRole('link', { name: 'Купить' }).first()).toBeVisible();
    await expect(page.locator('body')).toContainText('Заказать звонок');
    await page.locator('.button__burger').click();
    await page.getByRole('link', { name: 'Автоподбор' }).click();
    await expect(page.getByRole('link', { name: 'Купить' }).first()).toBeVisible();
    await expect(page.locator('body')).toContainText('Заказать звонок');
    await page.locator('.button__burger').click();
    await page.getByRole('link', { name: 'Акции' }).click();
    await expect(page.getByRole('link', { name: 'Купить' }).first()).toBeVisible();
    await expect(page.locator('body')).toContainText('Заказать звонок');
    await page.locator('.button__burger').click();
    await page.getByRole('link', { name: 'Контакты' }).first().click();
    await expect(page.getByRole('link', { name: 'Купить' }).first()).toBeVisible();
    await expect(page.locator('body')).toContainText('Заказать звонок');
    await page.locator('.button__burger').click();
    await page.getByRole('link', { name: 'Партнерам' }).first().click();
    await expect(page.getByRole('link', { name: 'Купить' }).first()).toBeVisible();
    await expect(page.locator('body')).toContainText('Заказать звонок');
    await page.locator('.button__burger').click();
    await page.getByRole('link', { name: 'О компании' }).first().click();
    await expect(page.getByRole('link', { name: 'Купить' }).first()).toBeVisible();
    await expect(page.locator('body')).toContainText('Заказать звонок');
    await page.locator('.button__burger').click();
    await page.getByRole('link', { name: 'Новости' }).click();
    await expect(page.getByRole('link', { name: 'Купить' }).first()).toBeVisible();
    await expect(page.locator('body')).toContainText('Заказать звонок');
    await page.locator('.button__burger').click();
    await page.getByRole('link', { name: 'Вакансии' }).first().click();
    await expect(page.getByRole('link', { name: 'Купить' }).first()).toBeVisible();
    await expect(page.locator('body')).toContainText('Заказать звонок');
    await page.locator('.button__burger').click();
    await page.getByRole('link', { name: 'Услуги' }).click();
    await expect(page.getByRole('link', { name: 'Купить' }).first()).toBeVisible();
    await expect(page.locator('body')).toContainText('Заказать звонок');
    await page.locator('.button__burger').click();
    await page.getByRole('link', { name: 'Автокредитование', exact: true }).click();
    await expect(page.getByRole('link', { name: 'Купить' }).first()).toBeVisible();
    await expect(page.locator('body')).toContainText('Заказать звонок');
    await page.locator('.button__burger').click();
    await page.getByRole('link', { name: 'Страхование', exact: true }).click();
    await expect(page.getByRole('link', { name: 'Купить' }).first()).toBeVisible();
    await expect(page.locator('body')).toContainText('Заказать звонок');
    await page.locator('.button__burger').click();
    await page.getByRole('link', { name: 'Шинный центр', exact: true }).click();
    await expect(page.getByRole('link', { name: 'Купить' }).first()).toBeVisible();
    await expect(page.locator('body')).toContainText('Заказать звонок');
    await page.locator('.button__burger').click();
    await page.getByRole('link', { name: 'Техосмотр' }).click();
    await expect(page.getByRole('link', { name: 'Купить' }).first()).toBeVisible();
    await expect(page.locator('body')).toContainText('Заказать звонок');
    await page.locator('.button__burger').click();
    await page.getByRole('link', { name: 'Сервисное обслуживание' }).click();
    await expect(page.getByRole('link', { name: 'Купить' }).first()).toBeVisible();
    await expect(page.locator('body')).toContainText('Заказать звонок');
    await page.locator('.button__burger').click();
    await page.getByRole('link', { name: 'Ремонт двигателя' }).click();
    await expect(page.getByRole('link', { name: 'Купить' }).first()).toBeVisible();
    await expect(page.locator('body')).toContainText('Заказать звонок');
    await page.locator('.button__burger').click();
    await page.getByRole('link', { name: 'Ремонт АКПП' }).click();
    await expect(page.getByRole('link', { name: 'Купить' }).first()).toBeVisible();
    await expect(page.locator('body')).toContainText('Заказать звонок');
    await page.locator('.button__burger').click();
    await page.getByRole('link', { name: 'Замена масла' }).click();
    await expect(page.getByRole('link', { name: 'Купить' }).first()).toBeVisible();
    await expect(page.locator('body')).toContainText('Заказать звонок');
    
  });

  test('Наличие нижней менюшки на всех страницах', async ({ page }) => {
    await page.goto('http://xn--80aej9alefdt2f.xn--p1ai/');
    await page.getByRole('link', { name: 'Купить' }).first().click();
    await expect(page.getByRole('contentinfo').getByRole('link', { name: 'О компании' })).toBeVisible();
    await expect(page.getByRole('contentinfo')).toContainText('Политика конфиденциальности');
    // await expect(page.getByRole('link', { name: 'Каталог шин' }).first()).toBeVisible();
    // await expect(page.locator('body')).toContainText('Заказать звонок');
    await page.locator('.button__burger').click();
    await page.getByRole('link', { name: 'Купить' }).nth(1).click();
    await expect(page.getByRole('contentinfo').getByRole('link', { name: 'О компании' })).toBeVisible();
    await expect(page.getByRole('contentinfo')).toContainText('Политика конфиденциальности');
    await page.locator('.button__burger').click();
    await page.getByRole('link', { name: 'Продать' }).nth(1).click();
    await expect(page.getByRole('contentinfo').getByRole('link', { name: 'О компании' })).toBeVisible();
    await expect(page.getByRole('contentinfo')).toContainText('Политика конфиденциальности');
    await page.locator('.button__burger').click();
    await page.getByRole('link', { name: 'Каталог шин' }).nth(1).click();
    await expect(page.getByRole('contentinfo').getByRole('link', { name: 'О компании' })).toBeVisible();
    await expect(page.getByRole('contentinfo')).toContainText('Политика конфиденциальности');
    await page.locator('.button__burger').click();
    await page.getByRole('link', { name: 'Автоподбор' }).click();
    await expect(page.getByRole('contentinfo').getByRole('link', { name: 'О компании' })).toBeVisible();
    await expect(page.getByRole('contentinfo')).toContainText('Политика конфиденциальности');
    await page.locator('.button__burger').click();
    await page.getByRole('link', { name: 'Акции' }).click();
    await expect(page.getByRole('contentinfo').getByRole('link', { name: 'О компании' })).toBeVisible();
    await expect(page.getByRole('contentinfo')).toContainText('Политика конфиденциальности');
    await page.locator('.button__burger').click();
    await page.getByRole('link', { name: 'Контакты' }).first().click();
    await expect(page.getByRole('contentinfo').getByRole('link', { name: 'О компании' })).toBeVisible();
    await expect(page.getByRole('contentinfo')).toContainText('Политика конфиденциальности');
    await page.locator('.button__burger').click();
    await page.getByRole('link', { name: 'Партнерам' }).first().click();
    await expect(page.getByRole('contentinfo').getByRole('link', { name: 'О компании' })).toBeVisible();
    await expect(page.getByRole('contentinfo')).toContainText('Политика конфиденциальности');
    await page.locator('.button__burger').click();
    await page.getByRole('link', { name: 'О компании' }).first().click();
    await expect(page.getByRole('contentinfo').getByRole('link', { name: 'О компании' })).toBeVisible();
    await expect(page.getByRole('contentinfo')).toContainText('Политика конфиденциальности');
    await page.locator('.button__burger').click();
    await page.getByRole('link', { name: 'Новости' }).click();
    await expect(page.getByRole('contentinfo').getByRole('link', { name: 'О компании' })).toBeVisible();
    await expect(page.getByRole('contentinfo')).toContainText('Политика конфиденциальности');
    await page.locator('.button__burger').click();
    await page.getByRole('link', { name: 'Вакансии' }).first().click();
    await expect(page.getByRole('contentinfo').getByRole('link', { name: 'О компании' })).toBeVisible();
    await expect(page.getByRole('contentinfo')).toContainText('Политика конфиденциальности');
    await page.locator('.button__burger').click();
    await page.getByRole('link', { name: 'Услуги' }).click();
    await expect(page.getByRole('contentinfo').getByRole('link', { name: 'О компании' })).toBeVisible();
    await expect(page.getByRole('contentinfo')).toContainText('Политика конфиденциальности');
    await page.locator('.button__burger').click();
    await page.getByRole('link', { name: 'Автокредитование', exact: true }).click();
    await expect(page.getByRole('contentinfo').getByRole('link', { name: 'О компании' })).toBeVisible();
    await expect(page.getByRole('contentinfo')).toContainText('Политика конфиденциальности');
    await page.locator('.button__burger').click();
    await page.getByRole('link', { name: 'Страхование', exact: true }).click();
    await expect(page.getByRole('contentinfo').getByRole('link', { name: 'О компании' })).toBeVisible();
    await expect(page.getByRole('contentinfo')).toContainText('Политика конфиденциальности');
    await page.locator('.button__burger').click();
    await page.getByRole('link', { name: 'Шинный центр', exact: true }).click();
    await expect(page.getByRole('contentinfo').getByRole('link', { name: 'О компании' })).toBeVisible();
    await expect(page.getByRole('contentinfo')).toContainText('Политика конфиденциальности');
    await page.locator('.button__burger').click();
    await page.getByRole('link', { name: 'Техосмотр' }).click();
    await expect(page.getByRole('contentinfo').getByRole('link', { name: 'О компании' })).toBeVisible();
    await expect(page.getByRole('contentinfo')).toContainText('Политика конфиденциальности');
    await page.locator('.button__burger').click();
    await page.getByRole('link', { name: 'Сервисное обслуживание' }).click();
    await expect(page.getByRole('contentinfo').getByRole('link', { name: 'О компании' })).toBeVisible();
    await expect(page.getByRole('contentinfo')).toContainText('Политика конфиденциальности');
    await page.locator('.button__burger').click();
    await page.getByRole('link', { name: 'Ремонт двигателя' }).click();
    await expect(page.getByRole('contentinfo').getByRole('link', { name: 'О компании' })).toBeVisible();
    await expect(page.getByRole('contentinfo')).toContainText('Политика конфиденциальности');
    await page.locator('.button__burger').click();
    await page.getByRole('link', { name: 'Ремонт АКПП' }).click();
    await expect(page.getByRole('contentinfo').getByRole('link', { name: 'О компании' })).toBeVisible();
    await expect(page.getByRole('contentinfo')).toContainText('Политика конфиденциальности');
    await page.locator('.button__burger').click();
    await page.getByRole('link', { name: 'Замена масла' }).click();
    await expect(page.getByRole('contentinfo').getByRole('link', { name: 'О компании' })).toBeVisible();
    await expect(page.getByRole('contentinfo')).toContainText('Политика конфиденциальности');    
  });
})